### ISSUE TITLE
json

### ISSUE THREAD

**Issue by faxw3b** [Alexell/BlumBot#11]
Привет, можешь пожалуйста отправить json который был на https://alexell.pro/crypto/x-empire/data/?
Знаю что эта информация обновляется, но все же

**Comment by Alexell** [comment]
В этот файл нужно вносить данные каждый день, а я перестал это делать примерно 5 дней назад и удалил файл, он все равно уже бесполезен. Сделай сам, в чем проблема то? Вроде бы вот такая структура под мой бот была:
```json
{
    "2024-09-20": {
        "funds": {
            "regular": [
                "fund1",
                "fund2",
                "fund3"
            ],
            "special": "blum"
        }
    },
    "2024-09-21": {
        "funds": {
            "regular": [
                "fund1",
                "fund2",
                "fund3"
            ],
            "special": null
        }
    }
}
```
