### ISSUE TITLE
Подскажите по поводу нескольких сессий

### ISSUE THREAD

**Issue by knesfox** [Alexell/BlumBot#15]
Помогите разобраться. Бот позволяет создавать много сессий в папке sessions. Однако я не могу запустить их все в рамках одного бота. Как можно запустить все эти сессии вместе или поочередно? Ведь как я понимаю в файл .env мы можем записать только 1 вариант API_ID и API_HASH. А хочется запускать свои несколько сессий в одной командной строке.
Заранее спасибо всем кто откликнется.

**Comment by Alexell** [comment]
API_ID и API_HASH не связан с сессиями. Вы можете создать свое приложение и получить API_ID и API_HASH с любого вашего аккаунта, даже если с него не будете запускать бота. Дополнительно ничего делать не нужно, запускаете бота, он сам подхватит все сессии, которые вы добавили.
