### ISSUE TITLE
а я могу в env. сделать так чтобы бот не тратил билеты?

### ISSUE THREAD

**Issue by SmILeTheMobster** [Alexell/BlumBot#2]

**Comment by Alexell** [comment]
Нет, сейчас такой возможности нету, но могу сделать.
Для чего вам это, если не секрет?

**Comment by Alexell** [comment]
Готово. Обновите бот и добавьте `GAMES_ENABLED=False` в ваш `.env`

**Comment by SmILeTheMobster** [comment]
спасибо большое, да я хочу чуть подкопить билетов (пока они ещё не сгорают), потому что была же инфа что за билеты можно будет другую валюту получить
