### ISSUE TITLE
ошибки запросов 

### ISSUE THREAD

**Issue by ivan52605** [Alexell/BlumBot#3]
![2024-09-01_20-17-13](https://github.com/user-attachments/assets/f43d13a4-67c7-4c9a-a311-7403b9384965)

что делать

**Comment by ilya125625262** [comment]
Тоже самое

**Comment by ivan52605** [comment]
я чкутка изменил его код сейчас тестирую если всё хорошо я смогу поделится им с вами

**Comment by Alexell** [comment]
У меня такое иногда тоже случается:
![изображение](https://github.com/user-attachments/assets/00eca563-94fe-4f84-97f7-6bc9d7049ed3)

А иногда нормально играет:
![изображение](https://github.com/user-attachments/assets/c8a61fa4-c5b5-4602-922e-d7cbda7bc999)

Эта проблема не связана с моим ботом, это сам Blum кривой. Разве не замечали, что иногда пытаешься начать игру, а она не с первого раза начинается (в самом тг)? Так вот в такие моменты, под капотом обычно проходит какая-нибудь ошибка.

**Comment by Alexell** [comment]
Я сейчас дебажил игру заново и с уверенностью могу сказать, что запросы на play и claim игры в моем боте правильные.
![Screenshot_2](https://github.com/user-attachments/assets/3e08484f-6e7c-4408-b477-4b8c7a6a84b8)

Попутно обратите внимание, сколько в списке запросов с ошибкой, которые игра (клиент) делала сама, в том числе попытки начать игру.

**Comment by ivan52605** [comment]
я как раз над этим рабоал чтобы были задержки елси ощибки чтоб просто не флудить сервер блума

**Comment by ivan52605** [comment]
не учёл у меня ещё вылетали ошибки не авторизованного запроса решил путём условия ели такая ошибка есть то обновляем токен и сначала ибо я не хочу постоянно заходить на сервер где крутится бот и перезапускать его ибо он ещё ии может остановится из за большого количества ошибок

**Comment by ilya125625262** [comment]
> Я сейчас дебажил игру заново и с уверенностью могу сказать, что запросы на play и claim игры в моем боте правильные. ![Скриншот_2](https://private-user-images.githubusercontent.com/25535043/363571197-3e08484f-6e7c-4408-b477-4b8c7a6a84b8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyOTQxNDcsIm5iZiI6MTcyNTI5Mzg0NywicGF0aCI6Ii8yNTUzNTA0My8zNjM1NzExOTctM2UwODQ4NGYtNmU3Yy00NDA4LWI0NzctNGI4YzdhNmE4NGI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDE2MTcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1MDdhYzk3MDUxYjU5MGMxMTBlOTYxMmNiYzY5ZjgyM2Y1NTE0MWRmMmEzNTBiZDlkMTA3NGY3ZjQyODA5YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ozz8uuHVpKVXb4qmZgO9U7jENCBM2OIAofZmGkoWjss)
> 
> Попутно обратите внимание, сколько в списке запросов с ошибкой, которые игра (клиент) делала сама, в том числе попытки начать игру, которые уже делал я в игре. Нажимаешь Play, ничего не происходит, а в дебаге проходит ошибка 400.

Действительно, дело оказалось не в вашем боте, сегодня все работает без сбоев...
Огромное спасибо, за ваш не легкий труд и вклад для нас - (обычных юзеров вашего софта)!

**Comment by Alexell** [comment]
@ivan52605 то есть у вас 401 периодически появляются? Или 403? Есть предположения, с чем это связано? Логичнее переавторизацию делать только при них, потому что ошибки 400 или 500 не решатся переавторизацией, это просто траблы на сервере Blum.

**Comment by rixfou** [comment]
@Alexell Вы имели в виду 400 и _**520**_?

**Comment by ivan52605** [comment]
> @ivan52605 то есть у вас 401 периодически появляются? Или 403? Есть предположения, с чем это связано? Логичнее переавторизацию делать только при них, потому что ошибки 400 или 500 не решатся переавторизацией, это просто траблы на сервере Blum.

У меня вылазили и те и те я повторюсь не учёл того что сам blum кривой понял это позже сейчас всё работает отлично спасибо за помощь
