### ISSUE TITLE
Login successful

### ISSUE THREAD

**Issue by litvin1973** [Alexell/BlumBot#4]
Здравствуйте! Подскажите, blum в консоли сообщение о прокси пишет только при запуске, при первом подключении, а далее при работе, в следующих подключениях Login successful не пишет о прокси? Или это у меня прокси слетают и он работает без прокси? Спасибо.

**Comment by Alexell** [comment]
Бот два раза пишет про прокси. При запуске бота **один раз** напишет, что найдено столько-то сессий и столько-то прокси. И при запуске каждой сессии (1 раз для каждой сессии) пишет IP прокси или ошибку.
