### ISSUE TITLE
[Error] Try to auth

### ISSUE THREAD

**Issue by Visualua** [Alexell/BlumBot#5]
![image](https://github.com/user-attachments/assets/f9d269d3-a0f3-4e58-8bad-5af2d3bfc85b)

**Comment by rixfou** [comment]
![image](https://github.com/user-attachments/assets/74173cb2-6c5f-4178-8279-dafb74087f88)

**Comment by igorjok** [comment]
Тоже самое, отвалился бот

**Comment by HollySheeeet** [comment]
@Alexell wait fix? or use another bots?

**Comment by Qurbonsaid** [comment]
![image](https://github.com/user-attachments/assets/693bb28d-b562-4a45-b944-da63ca0064c4)
@Alexell I think it is same error? When next update?

**Comment by Alexell** [comment]
Now I'll see what happened there.
